name: invoice_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.7
  iconsax:
  google_fonts: 6.1.0
  pdf: ^3.10.8
  fl_chart: ^0.68.0
  flutter_svg: ^2.0.16
  intl:
  flutter_keyboard_visibility: ^6.0.0
  flutter_screenutil:
  json_annotation:
  cached_network_image:
  dartz:
  connectivity_plus:
  flutter_regex:
  diacritic:
  pinput:
  dotted_dashed_line:
  qr_flutter:
  mobile_scanner:
  toastification:
  infinite_scroll_pagination:
  geolocator:
  dropdown_search:
  flutter_spinkit:
  screenshot: ^3.0.0
  path_provider: ^2.1.5
  share: ^2.0.4
  open_filex: ^4.6.0
  url_launcher: ^6.3.1

  #Injection Dependance
  get_it:

  #SM & storage local
  get:
  get_storage:

  # Networking
  retrofit:
  dio:
  http:

  # Security utils
  flutter_dotenv:

  # Log local & remote call api
  logger: any
  talker_dio_logger:
  timelines_plus: ^1.0.6



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner:
  retrofit_generator:
  json_serializable:
  mockito:


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/svgs/
    - .env
  







  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  #
  
  
