name: invoice_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.7
  iconsax:
  get:
  google_fonts: 6.1.0
  pdf: ^3.10.8
  fl_chart: ^0.68.0
  flutter_svg: ^2.0.16


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  







  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  #
  
  
